#! /bin/sh

# Load User Services
sxhkd &
mpd &
~/.fehbg
~/.config/polybar/launch.sh &
~/.config/bspwm/applets &

### WM Configuration ###

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
