#!/bin/sh
while read file
do
        case "$1" in
        "C-r")
                convert -rotate 90 "$file" "$file" ;;
        "C-c")
		filetype=$(echo "$file" | awk -F . '{print $NF}')
		if [ $filetype = "png" ]; then
			xclip -se c -t image/png "$file"
		elif [ $filetype != "gif" ]; then
			convert "$file" "/tmp/clipboard.png"
			xclip -se c -t image/png "/tmp/clipboard.png"
		fi ;;
        "C-w")
                feh --bg-fill "$file" ;;
        "C-d")
                mv "$file" ~/.local/share/Trash ;;
        esac
done
